from fnmatch import fnmatch
import frappe


FAG_CACHE_KEY = "fag_policy_cache"
DESK_PATTERNS = [
    "/app/*", 
    "/api/method/frappe.*",
    "/api/method/frappe.desk.*",
    "/api/method/frappe.core.*",
    "/api/method/frappe.realtime.*",
    "/api/method/run_doc_method",
    "/assets/*",
    "/files/*",
    "/login", "/logout", 
    "/api/method/login", "/api/method/logout",
    "/api/method/erpnext.*",
    "/api/method/fag.guard.reset_fag_cache",
]

def _is_desk_request(path: str) -> bool:
    """Return True if the request is generated by Desk (UI)."""
    return any(fnmatch(path, p) for p in DESK_PATTERNS)


def _load_policies_from_db():
    """Load all FAG policies from DB into a cacheable dict."""
    policies = frappe.get_all(
        "FAG Access Policy",
        fields=[
            "name", "endpoint", 
            "method_get", "method_post", "method_delete",
            "method_put", "method_patch", "method_any"
        ],
    )

    policy_map = []

    for p in policies:
        allowed_users = frappe.get_all(
            "Allowed User", filters={"parent": p.name}, pluck="user"
        )
        allowed_roles = frappe.get_all(
            "Allowed Role", filters={"parent": p.name}, pluck="role"
        )

        policy_map.append({
            "endpoint": p.endpoint.strip(),
            "methods": {
                "GET": p.method_get,
                "POST": p.method_post,
                "DELETE": p.method_delete,
                "PUT": p.method_put,
                "PATCH": p.method_patch,
                "ANY": p.method_any
            },
            "allowed_users": set(allowed_users),
            "allowed_roles": set(allowed_roles)
        })

    frappe.cache().set_value(FAG_CACHE_KEY, policy_map)
    return policy_map


def _get_policies():
    """Fetch cached policies or load from DB if not cached."""
    policies = frappe.cache().get_value(FAG_CACHE_KEY)
    if policies is None:
        policies = _load_policies_from_db()
    return policies


def _deny_access(message: str, code:int=403):
    throw_on_guard = frappe.cint(frappe.get_single_value("FAG Settings", "throw_on_guard"))

    frappe.local.response["http_status_code"] = code
    frappe.local.response["message"] = frappe._(message)
    frappe.response.update(frappe.local.response)
    
    if throw_on_guard == 1:
        frappe.throw(frappe._(message), frappe.PermissionError)
    
    # TODO: does this have any effect?? or can be passed down to the handling function
    frappe.local.flags.stop_execution = True

@frappe.whitelist()
def reset_fag_cache():
    frappe.cache().delete_value(FAG_CACHE_KEY)
    _load_policies_from_db()
    return "Cache reset successful"


def endpoint_guard():
    """Main FAG access check. Call this early in request processing."""
    request_path = frappe.request.path
    request_method = frappe.request.method.upper()
    user = frappe.session.user

    guard_enabled = frappe.cint(frappe.get_single_value("FAG Settings", "is_enabled"))

    if guard_enabled == 0:
        return

    if not (request_path.startswith("/api/method/") or request_path.startswith("/api/resource/")):
        return

    # TODO: they are already seeded by now, it gives control to the user if there are changes
    # if _is_desk_request(request_path) is True:
    #     return

    for policy in _get_policies():
        if fnmatch(request_path, policy["endpoint"]):
            if not policy["methods"]["ANY"]:
                if not policy["methods"].get(request_method, 0):
                    return _deny_access("HTTP method not allowed for this endpoint", code=405)

            if policy["allowed_users"] and user not in policy["allowed_users"]:
                return _deny_access("User not allowed to access this endpoint")

            if policy["allowed_roles"]:
                user_roles = set(frappe.get_roles(user))
                if not user_roles.intersection(policy["allowed_roles"]):
                    return _deny_access("Role not allowed to access this endpoint")

            return

    return _deny_access("Access denied!")


def after_install(*args, **kwargs):
    for ep in DESK_PATTERNS:
        if not frappe.db.exists("FAG Access Policy", {"endpoint": ep}):
            doc = frappe.get_doc({
                "doctype": "FAG Access Policy",
                "endpoint": ep,
                "method_any": 1
            })
            doc.insert(ignore_permissions=True)

    frappe.db.commit()
    _load_policies_from_db()
